"""The :mod:`streamlit_app` serves as a demo application to show the poetry generation API system at work.
This runs on sreamlit
"""
# Author: Xinkai Chen

import requests
import streamlit as st
import SessionState

base_url = "http://127.0.0.1:8080"
retrieval_endpoint = "retrieve"


def app():
    st.title("Youshen Poetry Generator")
    st.write("Guess which poem is written by our lovely AI!")  # description
    session_state = SessionState.get(name="", button_sent=False, data="")

    if st.button("Give me some poems"):
        session_state.button_sent = True
        # select poems and keep data in session_state so it's not refreshed when guessing
        response = requests.post(f"{base_url}/{retrieval_endpoint}")
        data = response.json()
        session_state.data = data

    if session_state.button_sent:
        # retrive data from session_state
        data = session_state.data
        if data["success"]:
            text1 = data["text1"]
            text2 = data["text2"]
            ground_truth = data["ground_truth"]
            human_text_idx = data["human_text_idx"]
            model_text_idx = data["model_text_idx"]
            st.subheader("Poem 1")
            st.write(text1)
            st.subheader("Poem 2")
            st.write(text2)
            st.subheader("Which one is generated by our model?")
            if st.button("Poem 1"):
                if ground_truth == "0":
                    st.write("Okay you are right! We did not fool you this time!")
                else:
                    st.write("It is a human-generated poem! We got you!")
                with open('user_guesses.txt', 'a') as f:
                    f.write("human_text_idx: {0}, model_text_idx: {1}, guess: {2}, ground_truth: {3}".format(
                        str(human_text_idx), str(model_text_idx), "0", ground_truth) + "\n")

            if st.button("Poem 2"):
                if ground_truth == "1":
                    st.write("Okay you are right! We did not fool you this time!")
                else:
                    st.write("It is a human-generated poem! We got you!")
                with open('user_guesses.txt', 'a') as f:
                    f.write("human_text_idx: {0}, model_text_idx: {1}, guess: {2}, ground_truth: {3}".format(
                        str(human_text_idx), str(model_text_idx), "1", ground_truth) + "\n")