version: "3.3"

services:
  web:
    build: ./
    command: streamlit run app.py --server.port 80
    volumes:
      - ./:/app
    ports:
      - 80:80

  main:
    build: ./
    command: uvicorn main:app --reload --workers 4 --host 0.0.0.0 --port 8000
    volumes:
      - ./:/app
    ports:
      - 8000:8000
